# Generated by Django 3.2.15 on 2022-08-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220816_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='farmer_id',
            new_name='farmer',
        ),
    ]
