# Generated by Django 3.2.15 on 2022-08-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_farmer_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_datetm', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('is_packed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-id'],
            },
        ),
    ]
