# Generated by Django 3.2.15 on 2022-08-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to='api.farmer'),
        ),
    ]
