# Generated by Django 3.2.15 on 2022-08-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='order',
        ),
    ]
