# Generated by Django 3.2.15 on 2022-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_package_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
