# Generated by Django 3.2.15 on 2022-08-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_package_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
    ]
