# Generated by Django 3.2.15 on 2022-08-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220827_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(default='89872345672', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.farmer'),
        ),
    ]
