# Generated by Django 3.2.15 on 2022-08-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220827_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='order_id',
            field=models.BigIntegerField(blank=True),
        ),
    ]
