# Generated by Django 3.2.15 on 2022-08-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_product_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='order_id',
            field=models.BigIntegerField(),
        ),
    ]
