# Generated by Django 3.2.15 on 2022-08-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_package_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to='api.farmer'),
            preserve_default=False,
        ),
    ]
