# Generated by Django 3.2.15 on 2022-08-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220827_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(default='89872345672', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to='api.farmer'),
        ),
    ]
