# Generated by Django 3.2.15 on 2022-09-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='farmer',
            new_name='user',
        ),
    ]
