# Generated by Django 3.2.15 on 2022-09-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_farmer_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='farmer',
        ),
    ]
