# Generated by Django 3.2.15 on 2022-09-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_user_product_farmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='farmer',
            new_name='user',
        ),
    ]
