# Generated by Django 3.2.15 on 2022-09-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20220919_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='ready_datetm',
            new_name='ready_at',
        ),
    ]
