# Generated by Django 3.2.15 on 2022-08-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220827_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliv_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
