# Generated by Django 3.2.15 on 2022-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20220827_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='898723456', max_length=20, null=True),
        ),
    ]
