# Generated by Django 3.2.15 on 2022-09-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_alter_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_datetime',
            new_name='created_at',
        ),
    ]
